[project]
name = "playground"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.14",
    "matplotlib>=3.10.3",
    "polars>=1.31.0",
    "polars-root>=0.1.0",
    "requests>=2.32.4",
]
